### PR TITLE
Add default.nix for Nix package manager.

### PR DESCRIPTION
**Pull request by ashgillman**
I thought you might be interested in seeing this @bathomas 

[Nix](https://nixos.org/nix/) is just a package manager, link apt-get, etc., but interesting in that its quite easy to write your own packages.

If you navigate to `petmr-rd-tools/` and type `nix-build`, it will automatically install cmake, boost, itk and glog, then run cmake and make, and install the tools to `./result/bin/`.

Not sure how much of interest it is to you guys, but worth a look. I also have packages for STIR, SIRF, etc.

### CODE REVIEW

**Comment by bathomas** [comment]
Can you add a comment to the top of the `nix` file stating that it belongs to the package and that you authored it? Then I'm happy to accept.

**Comment by ashgillman** [comment]
Done. But have you run it? I woudn't merge unless `n_users > 1`.

**Comment by ashgillman** [comment]
See also https://github.com/ashgillman/SIRF-NixBuild

**Comment by bathomas** [comment]
I have run it. Worked straight out of the box on Ubuntu 17.10.

**Pull request merged**
